name: Bug report
description: Describe the bug you encountered
title: "[Bug]: "
labels: ["bug", "report"]
projects: [USACE/screening-tool-ui]
assignees: ["everyone"]

body:   
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
      
  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        A clear and concise description of what the bug is.
    validations:
      required: true
      
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error    
    validations:
      required: true
      
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: |
        A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: system
    attributes:
      label: Device / System
      description: |
        - Device: desktop, laptop, phone
        - OS: Windows, MacOS, Ubuntu
        - Browser: Internet Explorer, Edge, Safari, Firefox, Chrome
        - Version: Version 120.0.6099.234 (Official Build) (x86_64)         
    validations:
      required: true
      
  - type: textarea
    id: screenshot
    attributes:
      label: Screenshots
      description: |
        If applicable, add screenshots to help explain your problem.
    validations:
      required: false
      
  - type: textarea
    id: details
    attributes:
      label: Additional Details
      description: |
        Any other details are much appreciated. 
    validations:
      required: false
  
  - type: markdown
    attributes:
      value: "Thanks for completing our form!"

