name: Feature request
description: Describe the feature you would like to add
title: "[Feature Request]: "
labels: ["raw-request", "enhancement"]
projects: ["USACE/CHART"]
assignees: ["everyone"]

body:    
  - type: textarea
    id: background
    attributes:
      label: Background
      description: |
        A short description of the background regarding this particular user story. If clarity is 
        needed to define the background for the user persona and general need for achieving the 
        objective, this is a good place to put it.
    validations:
      required: true
      
  - type: textarea
    id: user_story
    attributes:
      label: User Story
      description: |
        As a \<role\>, I want to \<do something\> \<with some frequency\> so that I can/will achieve \<some goal/objective\>.
    validations:
      required: true
      
  - type: textarea
    id: purpose
    attributes:
      label: Purpose
      description: |
        Please describe how the feature will accomplish the goal/objective.    
    validations:
      required: true
      
  - type: textarea
    id: workflow
    attributes:
      label: Workflow
      description: |
        Please describe some more detail on how you want to do the thing you want to do.    
    validations:
      required: false

  - type: textarea
    id: requirements
    attributes:
      label: Requirements
      description: |
        Any notes on requirements - this will help track progress on the user story.    
    validations:
      required: false
      
  - type: textarea
    id: misc
    attributes:
      label: Misc. Notes
      description: |
        Any other notes are much appreciated. 
    validations:
      required: false
  
  - type: markdown
    attributes:
      value: "Thanks for completing our form!"

